name: Deploy Client to Liara

on:
  push:
    branches:
      - design-home-page
    paths:
      - 'client/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Liara
        run: |
          npm install -g @liara/cli
          liara deploy --app=shoil-client --path=./client --platform=react --api-token=${{ secrets.LIARA_API_TOKEN }} --detach
