name: Deploy Server to Liara

on:
  push:
    branches:
      - design-home-page
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Liara
        run: |
          npm install -g @liara/cli
          liara deploy --app=shoil-server --path=./server --platform=node --port=5000 --api-token=${{ secrets.LIARA_API_TOKEN }} --detach
